import type { Metadata } from "next";
import "./globals.css";
import { Inter, Sora } from "next/font/google";
import ReactQueryProvider from "./providers/reactQueryProvider";
import SessionProviderWrapper from "./providers/SessionProviderWrapper";
import Navbar from "./component/Navbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const sora = Sora({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sora",
  weight: ["400", "500", "600", "700"], // pick what you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
          crossOrigin="anonymous"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link rel="dns-prefetch" href="https://locationiq.org" />
      </head>
      <body className={`${sora.variable} ${inter.variable} antialiased`}>
        <SessionProviderWrapper>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </SessionProviderWrapper>
        <Navbar />
      </body>
    </html>
  );
}
